### ISSUE TITLE
4pisky broker "iamalive"s are reported as "unrecognised root tag"

### ISSUE THREAD

**Issue by martinjohndyer** [lpsinger/pygcn#4]
Listening to the [4pisky broker](https://4pisky.org/voevents/) instead of the default NASA GCN/TAN server reports an error every time an `iamalive` comes in, and after 2 minutes the connection keeps getting reset. 

Testing is simple, just listen to `voevent.4pisky.org` and wait for a few minutes:
```
$ pygcn-listen voevent.4pisky.org
INFO:gcn.listen:connected to voevent.4pisky.org:8099
ERROR:gcn.listen:received XML document with unrecognized root tag: {http://www.telescope-networks.org/xml/Transport/v1.1}Transport
INFO:gcn.listen:received VOEvent
INFO:gcn.handlers.archive:archived ivo://nasa.gsfc.gcn/Fermi#Point_Dir_2018-10-25T14:50:00.00_000000-0-311
ERROR:gcn.listen:received XML document with unrecognized root tag: {http://www.telescope-networks.org/xml/Transport/v1.1}Transport
ERROR:gcn.listen:socket error
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 218, in listen
    _ingest_packet(sock, ivorn, handler, log)
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 140, in _ingest_packet
    payload = _recv_packet(sock)
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 107, in _recv_packet
    payload_len, = _size_struct.unpack_from(_recvall(sock, _size_len))
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 96, in _recvall
    raise socket.error('connection closed by peer')
OSError: connection closed by peer
INFO:gcn.listen:closed socket
INFO:gcn.listen:connected to voevent.4pisky.org:8099
ERROR:gcn.listen:received XML document with unrecognized root tag: {http://www.telescope-networks.org/xml/Transport/v1.1}Transport
ERROR:gcn.listen:received XML document with unrecognized root tag: {http://www.telescope-networks.org/xml/Transport/v1.1}Transport
ERROR:gcn.listen:socket error
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 218, in listen
    _ingest_packet(sock, ivorn, handler, log)
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 140, in _ingest_packet
    payload = _recv_packet(sock)
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 107, in _recv_packet
    payload_len, = _size_struct.unpack_from(_recvall(sock, _size_len))
  File "/home/martin/.local/lib/python3.5/site-packages/gcn/voeventclient.py", line 96, in _recvall
    raise socket.error('connection closed by peer')
OSError: connection closed by peer
INFO:gcn.listen:closed socket
...
```

Output from running with DEBUG logging:
```
INFO:test:connected to voevent.4pisky.org:8099
DEBUG:test:received packet of 464 bytes
DEBUG:test:payload is:
b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<trn:Transport xmlns:trn="http://www.telescope-networks.org/xml/Transport/v1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:schemaLocation="http://telescope-networks.org/schema/Transport/v1.1 http://www.telescope-networks.org/schema/Transport-v1.1.xsd" role="authenticate">\n  <Origin>ivo://voevent.4pisky.org/voevent-receive</Origin>\n  <TimeStamp>2018-10-25T14:50:39Z</TimeStamp>\n</trn:Transport>\n'
ERROR:test:received XML document with unrecognized root tag: {http://www.telescope-networks.org/xml/Transport/v1.1}Transport
```

---

This seems to arise due to the following check looking for a root tag of

<pre>
{http://telescope-networks.org/<b>schema</b>/Transport/v1.1}Transport
</pre>

but not 4pisky's
<pre>
{http://telescope-networks.org/<b>xml</b>/Transport/v1.1}Transport
</pre>

https://github.com/lpsinger/pygcn/blob/abd4454e21229439f9699eb3c9a836c857e05447/gcn/voeventclient.py#L157-L166

It should be a simple fix to allow either, although it's not a critical error (since the connection is restored and actual events are still handled) it would save having to reconnect and prevent filling up the logs with unnecessary error messages.

**Comment by lpsinger** [comment]
Good catch. Is this a bug in pygcn or in 4pisky? The [IVOA VOEvent Transport Protocol recommendation](http://www.ivoa.net/documents/VOEventTransport/20170320/REC-VTP-2.0-20170320.html) calls for `xmlns:trn="http://telescope-networks.org/schema/Transport/v1.1"`.

**Comment by martinjohndyer** [comment]
You're right, seems like it might be 4pisky deviating from the definition. I'll try and contact them.
